name: Train

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      run: |
        docker build -t sskm1996/assign_cicd:latest .
    - name: Docker Login
      run: |
        docker login -u "sskm1996" -p "${{ secrets.DOCKER_PASS }}"
    - name: Push Docker image
      run: |
        docker push sskm1996/assign_cicd:latest
